name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 21 * * *"
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.23.2"
      - run: deno run -A generate.ts
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: your-project-name
          entrypoint: index.js
          root: dist
